# Generated by Django 4.2 on 2024-01-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogpost', '0003_alter_blogpost_slug_alter_blogpost_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=355, unique=True),
        ),
    ]
